---
title: "Draft R Markdown document"
author: "Your Name"
output: html_document
---

```{r setup}
library(vroom)
library(here)
library(vroom)
library(purrr)
library(fs)
source(here("R/functions.R")) 
options(dplyr.summarise.inform = FALSE)
```

## Importing raw data

```{r}
user_1_info_file <-here("data-raw/mmash/user_1/user_info.csv")
user_1_info_data <- vroom(
    user_1_info_file,
    col_select = -1,
    col_types = cols(
        gender = col_character(),
        weight = col_double(),
        height = col_double(),
        age = col_double(),
        .delim = ","
    ),
    .name_repair = snakecase::to_snake_case
)

```

## Exercise: Import the saliva data

```{r}
user_1_saliva_file <- here("data-raw/mmash/user_1/saliva.csv")

user_1_saliva_data_prep <- vroom(
    user_1_saliva_file,
    col_select = -1,
    .name_repair = snakecase::to_snake_case
)

spec(user_1_saliva_data_prep)

user_1_saliva_data <- vroom(
    user_1_saliva_file,
    col_select = -1,
    col_types = cols(
        col_skip(),
        samples = col_character(),
        cortisol_norm = col_double(),
        melatonin_norm = col_double(),
        .delim = ","
    ),
    .name_repair = snakecase::to_snake_case
)

import_saliva(here::here("data-raw/mmash/user_1/saliva.csv"))
```

## Import larger datasets
```{r}
user_1_rr_file <- here("data-raw/mmash/user_1/RR.csv")
user_1_rr_data_prep <- vroom(
    user_1_rr_file,
    n_max = 100,
    col_select = -1,
    .name_repair = snakecase::to_snake_case
)

spec(user_1_rr_data_prep)

user_1_rr_data <- vroom(
    user_1_rr_file,
    col_select = -1,
    col_types = cols(
        ibi_s = col_double(),
        day = col_double(),
        # Converts to seconds
        time = col_time(format = "")
    ),
    .name_repair = snakecase::to_snake_case
) 


import_rr(here::here("data-raw/mmash/user_1/RR.csv"))
```

## Exercise: Import the Actigraph data.
```{r}
user_1_actigraph_file <- here("data-raw/mmash/user_1/Actigraph.csv")
user_1_actigraph_data_prep <- vroom(
    user_1_actigraph_file,
    n_max = 100,
    col_select = -1,
    .name_repair = snakecase::to_snake_case
)
spec(user_1_actigraph_data_prep)


import_actigraph(here::here("data-raw/mmash/user_1/Actigraph.csv"))
```

## Making a function

```{r}
#' Add two numbers together.
#'
#' @param num1 A number here.
#' @param num2 A number here.
#'
#' @return Returns the sum of the two numbers.
#'
add_numbers <- function(num1, num2) {
    added <- num1 + num2
    return(added)
}
```
```{r}
import_user_info(here("data-raw/mmash/user_1/user_info.csv"))
```


## Exercise for importing the saliva data as a function.

```{r}



# Test that the function works
import_saliva(here("data-raw/mmash/user_1/saliva.csv"))
```


## Exercise: Map on the other datasets

```{r}
user_info_files <- fs::dir_ls(here::here("data-raw/mmash/"), 
                          regexp = "user_info.csv", 
                          recurse = TRUE)

user_info_df <- map_dfr(user_info_files, import_user_info,
                        .id = "file_path_id")

```

```{r}
#' Import multiple MMASH data files and merge into one data frame.
#'
#' @param file_pattern Pattern for which data file to import.
#' @param import_function Function to import the data file.
#'
#' @return A single data frame/tibble.
#'
import_multiple_files <- function(file_pattern, import_function) {
    data_files <- fs::dir_ls(here::here("data-raw/mmash/"),
                             regexp = file_pattern,
                             recurse = TRUE)
    
    combined_data <- purrr::map_dfr(data_files, import_function,
                                    .id = "file_path_id")
    return(combined_data)
}

# Test on saliva in the Console
import_multiple_files("saliva.csv", import_saliva)
```

```{r}
rr_df <- import_multiple_files("RR.csv", import_rr)

rr_df %>% 
    group_by(file_path_id, day) %>% 
    summarise(across(ibi_s, list(mean = mean), na.rm = TRUE))
```
# Summase mean and standard deviation

```{r}
summaried_rr_df <- rr_df %>% 
    group_by(file_path_id, day) %>% 
    summarise(across(ibi_s, list(mean = mean, sd = sd), na.rm = TRUE)) %>% 
    ungroup()

summaried_rr_df
```
## Exercise: Summarise Actigraph

```{r}
actigraph_df <-import_multiple_files("Actigraph.csv", import_actigraph)
summarised_actigraph_df <- actigraph_df %>% 
    group_by(file_path_id, day) %>% 
    summarise(across(steps, list(mean = mean, sd = sd), na.rm = TRUE)) %>% 
    ungroup()

```

